### ISSUE TITLE
Villagers crash the game

### ISSUE THREAD

**Issue by Mewtwoy** [frqnny/mostructures#16]
Description: Ticking entity

java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at net.minecraft.entity.ai.brain.task.GoToWorkTask.run(GoToWorkTask:531)
    at net.minecraft.entity.ai.brain.task.GoToWorkTask.run(GoToWorkTask:23)
    at net.minecraft.entity.ai.brain.task.Task.tryStarting(Task:49)
    at net.minecraft.entity.ai.brain.Brain.startTasks(Brain:506)
    at net.minecraft.entity.ai.brain.Brain.tick(Brain:465)
    at net.minecraft.entity.passive.VillagerEntity.mobTick(VillagerEntity:272)
    at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:744)
    at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2508)
    at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:542)
    at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
    at net.minecraft.entity.LivingEntity.tick(LivingEntity:2254)
    at net.minecraft.entity.mob.MobEntity.tick(MobEntity:342)
    at net.minecraft.entity.passive.VillagerEntity.tick(VillagerEntity:313)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
    at net.minecraft.class_3218$$Lambda$7489/1322030875.accept(Unknown Source)
    at net.minecraft.world.World.tickEntity(World:561)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at net.minecraft.server.MinecraftServer$$Lambda$7048/1043748215.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

Mods which potentially have issues: Repurposed structures, glimmering potions.
I removed mods one by one, until i narrowed it down to these.

**Comment by frqnny** [comment]
we don't even touch villager AI but okay, gotta love optionals.
