### ISSUE TITLE
Snapshot version crash

### ISSUE THREAD

**Issue by Greg-J** [frqnny/mostructures#29]
On 21w07 using seed -6316420307748711466. Travel West when you spawn and slightly after you see the pillager outpost render, the game will crash. Verified twice and verified working when mod was removed.

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/8/21 3:05 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.class_2899.<init>(Lnet/minecraft/class_2540;)V
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.createPacket(ServerLoginNetworkAddon.java:172)
	at net.fabricmc.fabric.api.networking.v1.PacketSender.sendPacket(PacketSender.java:68)
	at net.fabricmc.fabric.impl.networking.NetworkingImpl.lambda$init$0(NetworkingImpl.java:63)
	at net.fabricmc.fabric.impl.networking.NetworkingImpl$$Lambda$2590/649859852.onLoginStart(Unknown Source)
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.queryTick(ServerLoginNetworkAddon.java:82)
	at net.minecraft.class_3248.redirect$zgm000$handlePlayerJoin(class_3248.java:561)
	at net.minecraft.class_3248.method_18785(class_3248.java:66)
	at net.minecraft.class_2535.method_10754(class_2535.java:235)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:884)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.handler$zmn000$modifiedRunLoop(MinecraftServer.java:4810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:259)
	at net.minecraft.server.MinecraftServer$$Lambda$6048/1719916285.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 21w07a
	Minecraft Version ID: 21w07a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5726509360 bytes (5461 MB) / 7415529472 bytes (7072 MB) up to 12884901888 bytes (12288 MB)
	CPUs: 24
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		carpet: Carpet Mod in Fabric 1.4.27
		carpet-extra: Carpet Extra 1.4.27
		easiervillagertrading: EasierVillagerTrading 20w46a-fabric0.26.0-1.5.3
		fabric: Fabric API 0.31.2+1.17
		fabric-api-base: Fabric API Base 0.2.1+524a2e8559
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.4+1eb2670e59
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+92519afa59
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9d6353a59
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa59
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+524a2e8559
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+92519afa59
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afa59
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+524a2e8559
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afa59
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.6+0d6fddee59
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa59
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afa59
		fabric-item-api-v1: Fabric Item API (v1) 1.2.3+36b77c3e59
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+92519afa59
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+524a2e8559
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e59
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.3+40e100eb59
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afa59
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa59
		fabric-models-v0: Fabric Models (v0) 0.2.1+92519afa59
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+7268309e59
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+40e100eb59
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa59
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100eb59
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afa59
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afa59
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+92519afa59
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+92519afa59
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.6+92519afa59
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.1.0+2a1dabb659
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afa59
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+92519afa59
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa59
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+92519afa59
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.4+1eb2670ef7
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+e5686180f7
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+40e100eb59
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.6+7268309e59
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+92519afa59
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+92519afa59
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.9+36b77c3e59
		fabricloader: Fabric Loader 0.11.1
		itemscroller: Item Scroller 0.15.0-dev.20210204.184345
		java: Java HotSpot(TM) 64-Bit Server VM 8
		litematica: Litematica 0.0.0-dev.20210204.184419
		malilib: MaLiLib 0.10.0-dev.21+beta.1
		minecraft: Minecraft 1.17-alpha.21.7.a
		minihud: MiniHUD 0.19.0-dev.20210208.154935
		modmenu: Mod Menu 2.0.0-beta.2
		wi_zoom: WI Zoom 1.3-MC21w08a
		worldedit: WorldEdit 7.2.3-SNAPSHOT+5664-1f06af1
		wthit: wthit 3.1.1+21w05b
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by frqnny** [comment]
Mo' Structures's snapshot version only works on 20w08b right now, so either update to that. Also, for some reason the log doesn't show Mo' Structures loaded?...

**Comment by frqnny** [comment]
Well since new snapshots are coming out and the crahs u provided shows NO mo structures ima close
