### ISSUE TITLE
latest version crashes

### ISSUE THREAD

**Issue by Greg-J** [frqnny/mostructures#49]
Latest version of Fabric, MC 1.17.1, and Fabric API:

```
Jul 27 14:08:44 dekocraft3 java[31047]: [14:08:44] [main/ERROR]: Structure start: Not a JSON object: null; Not a JSON object: "more_structures:village_end_highlands"
Jul 27 14:08:44 dekocraft3 java[31047]: [14:08:44] [main/FATAL]: Failed to start the minecraft server
Jul 27 14:08:44 dekocraft3 java[31047]: com.google.gson.JsonParseException: Error loading registry data: Missing value [0] : ResourceKey[minecraft:worldgen/configured_structure_feature / more_structures:bastion_remnant_soul_sand_valley]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.class_5455.method_34849(class_5455.java:221) ~[intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.class_5455.method_30526(class_5455.java:221) ~[intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.class_5455.method_30519(class_5455.java:212) ~[intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.class_5382.method_36575(class_5382.java:57) ~[intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.class_5382.method_36574(class_5382.java:51) ~[intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.server.Main.redirect$zjd000$ofRegistryOps(Main.java:1051) ~[intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.minecraft.server.Main.main(Main.java:159) [intermediary-server.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
Jul 27 14:08:44 dekocraft3 java[31047]:         at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
```

**Comment by frqnny** [comment]
not mo structures?

**Comment by Greg-J** [comment]
I saw more_strucures and assumed. My bad.

**Comment by Greg-J** [comment]
> not mo structures?

I don't know what else this could be. Is `more_structures:village_end_highlands` not from more_structures?

**Comment by frqnny** [comment]
this is mo structures, not more structures. we also don’t add any structure called thatll
