### ISSUE TITLE
Config broken in 1.18.1 -- converting to default values.

### ISSUE THREAD

**Issue by itsdinkd** [frqnny/mostructures#59]
Your breaking your own config with your comment.

```
[02:07:47] [main/ERROR]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 10 path $.Here
[02:07:47] [main/INFO]: Encountered an error while reading mostructures-config-v2 config, falling back to default values.
[02:07:47] [main/INFO]: If this problem persists, delete the config file mostructures-config-v2.json5 and try again.```

here's my config, which I deleted before I updated to latest 1.18.1 version


```json
{
  // Welcome to Mo'Structures Config!

   Here, you can turn off structures, change their chance, and also change their salt.

   To turn off a structure, simply go to the corresponding entry and set `activated` to false.

   Mo' Structures uses the vanilla structure spawning system. That is-
   - Seperation is the minimum chunks between structures
   - Spacing is the average chunks between structures

   Salt is a special field that gives structures unique spawning positions. DO NOT TOUCH IT, ONLY ADVANCED TROUBLESHOOTING!


  "structureConfigEntries": {
    "villager_tower": {
      "activated": true,
      "seperation": 18,
      "spacing": 42,
      "salt": 550292492
    },
    "lighthouse": {
      "activated": true,
      "seperation": 22,
      "spacing": 44,
      "salt": 29502322
    },
    "air_balloon": {
      "activated": true,
      "seperation": 2,
      "spacing": 9,
      "salt": 29483148
    },
    "killer_bunny_castle": {
      "activated": true,
      "seperation": 40,
      "spacing": 60,
      "salt": 48123900
    },
    "jungle_pyramid": {
      "activated": true,
      "seperation": 11,
      "spacing": 31,
      "salt": 312178642
    },
    "abandoned_church": {
      "activated": true,
      "seperation": 16,
      "spacing": 38,
      "salt": 66996840
    },
    "volcanic_vent": {
      "activated": false,
      "seperation": 4,
      "spacing": 8,
      "salt": 84981094
    },
    "barn_house": {
      "activated": true,
      "seperation": 8,
      "spacing": 38,
      "salt": 165757306
    },
    "pirate_ship": {
      "activated": true,
      "seperation": 31,
      "spacing": 51,
      "salt": 583957395
    },
    "tavern": {
      "activated": true,
      "seperation": 18,
      "spacing": 46,
      "salt": 19296726
    },
    "moai": {
      "activated": true,
      "seperation": 7,
      "spacing": 19,
      "salt": 12994829
    },
    "village_bazaar": {
      "activated": false,
      "seperation": 16,
      "spacing": 32,
      "salt": 34842291
    },
    "the_castle_in_the_sky": {
      "activated": true,
      "seperation": 50,
      "spacing": 80,
      "salt": 423494938
    },
    "ice_tower": {
      "activated": true,
      "seperation": 24,
      "spacing": 48,
      "salt": 964058305
    },
    "villager_market": {
      "activated": true,
      "seperation": 16,
      "spacing": 36,
      "salt": 784939542
    },
    "big_pyramid": {
      "activated": true,
      "seperation": 15,
      "spacing": 30,
      "salt": 239284294
    },
    "pillager_factory": {
      "activated": true,
      "seperation": 27,
      "spacing": 62,
      "salt": 839204924
    }
  }
}

```

**Comment by itsdinkd** [comment]
This actually prevents server from loading. after testing, when it does the above ^ and breaks the config and goes to default, the server will prevent launching. You can delete the config, it will work, but then on 2nd launch of server, it crashes again with the error below.



```java
[02:25:50] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mostructures'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.5) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.11.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.11.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.11.jar:?]
Caused by: java.lang.NullPointerException: Tried StructureConfigEntry with id: mostructures:barn_house, but it was null!
        at io.github.frqnny.mostructures.config.MoStructuresConfig.get(MoStructuresConfig.java:48) ~[mostructures-1.3.0-pre2+1.18.jar:?]
        at io.github.frqnny.mostructures.util.RegUtils.registerStructure(RegUtils.java:54) ~[mostructures-1.3.0-pre2+1.18.jar:?]
        at io.github.frqnny.mostructures.util.RegUtils.registerStructure(RegUtils.java:68) ~[mostructures-1.3.0-pre2+1.18.jar:?]
        at io.github.frqnny.mostructures.MoStructures.registerStructures(MoStructures.java:74) ~[mostructures-1.3.0-pre2+1.18.jar:?]
        at io.github.frqnny.mostructures.MoStructures.onInitialize(MoStructures.java:217) ~[mostructures-1.3.0-pre2+1.18.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.11.jar:?]
        ... 15 more
        ```

**Comment by frqnny** [comment]
damn u serious

**Comment by frqnny** [comment]
damn u serious

**Comment by wackoamd1** [comment]
any solution to this , i wanted to download the mod until i saw this ;-(
