### ISSUE TITLE
Villager Market causes crash

### ISSUE THREAD

**Issue by GttiqwT** [frqnny/mostructures#65]
When walking towards a plains/forest biome my game will either black/grey screen and freeze. It finally crashed and heres the report. it said mostructures:village_market was the issue.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/26/22, 9:32 PM
Description: Feature placement

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3722$1 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3722.<init>(class_3722.java:40)
	at net.minecraft.class_3715.method_10123(class_3715.java:153)
	at net.minecraft.class_3233.method_8321(class_3233.java:223)
	at net.minecraft.class_3499.method_15172(class_3499.java:257)
	at net.minecraft.class_3781.method_16626(class_3781.java:126)
	at net.minecraft.class_3790.method_27236(class_3790.java:88)
	at net.minecraft.class_3790.method_14931(class_3790.java:84)
	at net.minecraft.class_3449.method_14974(class_3449.java:62)
	at net.minecraft.class_2794.method_38265(class_2794.java:279)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:278)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md4a796b$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 32 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/class_1657;)D in mixins.reach-entity-attributes.json:InventoryValidationMixin from mod reach-entity-attributes failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3722.<init>(class_3722.java:40)
	at net.minecraft.class_3715.method_10123(class_3715.java:153)
	at net.minecraft.class_3233.method_8321(class_3233.java:223)
	at net.minecraft.class_3499.method_15172(class_3499.java:257)
	at net.minecraft.class_3781.method_16626(class_3781.java:126)
	at net.minecraft.class_3790.method_27236(class_3790.java:88)
	at net.minecraft.class_3790.method_14931(class_3790.java:84)
	at net.minecraft.class_3449.method_14974(class_3449.java:62)
	at net.minecraft.class_2794.method_38265(class_2794.java:279)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:278)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md4a796b$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Feature --
Details:
	**Description: ResourceKey[minecraft:worldgen/structure_feature / mostructures:villager_market]**
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:278)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md4a796b$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Generation --
Details:
	CenterX: 197
	CenterZ: 51
	Seed: 2758689297153913754
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:278)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md4a796b$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Chunk to be generated --
Details:
	Location: 197,51
	Position hash: 219043332293
	Generator: net.minecraft.class_3754@56d3e9e2
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_3222['GttiqwT'/93, l='ServerLevel[New World]', x=3022.37, y=107.91, z=781.04]]
	Chunk stats: 4141
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,96,0), Section: (at 0,0,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 55370 game time, 76018 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 7025 (now: false), thunder time: 96184 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1922110240 bytes (1833 MiB) / 5767168000 bytes (5500 MiB) up to 8422162432 bytes (8032 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e98
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37480.12
	Virtual memory used (MB): 17767.38
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 175.01
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8032m -Xms256m
	Fabric Mods: 
		ae2: Applied Energistics 2 10.0.0
		appleskin: AppleSkin 2.3.0+mc1.18.1
		arcanus: Arcanus 1.27
		architectury: Architectury 3.7.33
		artifacts: Artifacts 6.0.0+fabric
		artifality: Artifality 0.5.5
		attributefix: AttributeFix 13.0.5
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.5
		balm-fabric: Balm 2.4.3+0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bclib: BCLib 1.3.5
		better_wandering_trader: Better Wandering Trader 1.8.0
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18-1.0
		betterend: Better End 1.0.3
		betternether: Better Nether 6.0.11
		bewitchment: Bewitchment 1.18-15
		blue_endless_jankson: jankson 1.2.1
		bookshelf: Bookshelf 12.0.22
		buriedbarrels: Buried Barrels 1.0.3.1
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		chisel: Chisel Refabricated 1.4.5
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+5
		controlling: Controlling For Fabric 9.0+15
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkutils: DarkUtilities 9.0.2
		detailab: Detail Armor Bar 2.6.1+1.18-fabric
		diggusmaximus: Diggus Maximus 1.5.3-1.18
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		equipmentcompare: Equipment Compare 1.2.11
		expandability: ExpandAbility 5.0.0
		fab: Foodables 1.2.0-1.18
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		fake-player-api: Fake Player API 0.3.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		heartytrinkets: Hearty Trinkets 1.18.1-1.0.0
		iceberg: Iceberg 1.0.38
		impersonate: Impersonate 2.4.0
		indium: Indium 1.0.2-alpha3+mc1.18.1
		indrev: Industrial Revolution 1.13.7-BETA
		iris: Iris 1.2.0-pre
		ironchests: Iron Chests for Fabric 1.5.4
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.5+1.14.4-1.18.2
		kyrptconfig: Kyrpt Config 1.3.8-1.18
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libgui: LibGui 5.3.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.3
		lightoverlay: Light Overlay 6.0.4
		lithium: Lithium 0.7.8
		magna: Magna 1.7.0-1.18-pre1
		megane: megane 7.1.3
		megane-api: megane-api 7.0.0
		megane-applied-energistics-2: megane-applied-energistics-2 7.0.1
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-industrial-revolution: megane-industrial-revolution 7.0.0
		megane-lib-block-attributes: megane-lib-block-attributes 7.0.0
		megane-reborn-core: megane-reborn-core 7.0.0
		megane-reborn-energy: megane-reborn-energy 7.0.0
		megane-runtime: megane-runtime 7.1.3
		megane-tech-reborn: megane-tech-reborn 7.0.0
		megane-vanilla: megane-vanilla 7.0.0
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.22
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		omega-config: OmegaConfig 1.1.0
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.2.0+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pigpen: PigPen 7.0.2
		playerabilitylib: Pal 1.5.0
		polymorph: Polymorph 0.0.20-1.18.2
		rangers_haven: Ranger's Haven 2.3.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.3.443
		runelic: Runelic 10.0.6
		smootherbedrock: Smoother Bedrock 1.0.4
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		taxfreelevels: Tax Free Levels 1.3
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		travelersbackpack: Traveler's Backpack 1.18.1-7.0.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		twm: The Wild Mod 0.6
		waystones: Waystones 9.0.4
		wthit: wthit 4.5.5
		xaerominimap: Xaero's Minimap 22.3.0
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yungsapi: YUNG's API 1.18-Fabric-36
		yungsextras: YUNG's Extras 1.18.1-1.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['GttiqwT'/93, l='ServerLevel[New World]', x=3022.37, y=107.91, z=781.04]]
	Data Packs: vanilla, file/datapack.zip, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by empty-window** [comment]
I'm having the same issue. It has something to do with the lectern block. It causes the villager market to crash and makes placing the lectern crash the game.

**Comment by frqnny** [comment]
I don't think it's my issue.

**Comment by GttiqwT** [comment]
im certain its this mod cause when I disabled the village market spawn it fixed my game and no more crashes. I even saw a sign/little structure with the village market so its definetly that.

**Comment by twixstix** [comment]
Just to let anyone else who sees this know, the problem is actually caused by Pehkui 3.2.0, not this mod. Update it to fix the crash.
